services:
  db:
    build:
      context: ./build
      dockerfile: Dockerfile
    image: postgres:ssl
    restart: unless-stopped
    container_name: postgres-database
    env_file:
      - "./.env"
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128 * 2 ^ 20 bytes = 128Mb
      - "./data:/var/lib/postgresql/data:rw"
    expose:
      - 5432
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: unless-stopped
    container_name: postgres-adminer
    ports:
      - 5480:8080
